'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, LogOut, Search, Sparkles, UserRound } from 'lucide-react'
import { gigs, students } from '@/lib/pipull-data'
import { rankMatches, getRoleLabel, type DemoAccount } from '@/lib/pipull-demo'
import type { Gig, Student } from '@/lib/pipull-data'
import { Avatar } from './avatar'
import { seededTradeCounts } from '@/lib/pipull-trades'

export function RoleDashboard({ account, onLogout, onBook, onHire }: { account: DemoAccount; onLogout: () => void; onBook: (gig: Gig) => void; onHire: (student: Student) => void }) {
  const [query, setQuery] = useState('')
  const rankedGigs = useMemo(() => rankMatches(query, gigs), [query])
  const rankedStudents = useMemo(() => rankMatches(query, students), [query])
  const isRecruiter = account.role === 'recruiter'

  return <main className="min-h-dvh bg-surface">
    <header className="border-b border-border bg-card"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8"><div><p className="font-mono text-sm font-bold tracking-[0.18em] text-brand">PIPULL</p><p className="mt-1 text-xs text-muted-foreground">{getRoleLabel(account.role)} dashboard</p></div><div className="flex items-center gap-3"><Avatar name={account.name} color="#2563eb" className="size-9 text-xs" /><span className="hidden text-sm font-semibold sm:block">{account.name}</span><button type="button" onClick={onLogout} className="rounded-lg p-2 text-muted-foreground transition hover:bg-surface hover:text-foreground" aria-label="Log out"><LogOut className="size-4" /></button></div></div></header>
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-sm font-semibold text-brand"><Sparkles className="size-4" /> Personalized matching</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">{isRecruiter ? 'Find trusted local talent.' : 'Find your next opportunity.'}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Describe what you need in plain language. We rank profiles and gigs by relevance, category fit, verified skills, and local context.</p></div></div>
      <label className="mt-8 flex min-h-14 items-center gap-3 rounded-2xl border border-input bg-card px-4 shadow-sm focus-within:border-brand focus-within:ring-4 focus-within:ring-brand/10"><Search className="size-5 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={isRecruiter ? 'Try “reliable bathroom cleaner near campus”' : 'Try “poster design for a club event”'} className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" /></label>
      {query ? <section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Top semantic matches</h2><span className="text-xs text-muted-foreground">Sorted by match accuracy</span></div><div className="mt-4 grid gap-4 md:grid-cols-2">{(isRecruiter ? rankedStudents : rankedGigs).slice(0, 6).map(({ item, score }) => 'title' in item ? <button type="button" key={item.id} onClick={() => onBook(item)} className="rounded-2xl border border-border bg-card p-4 text-left transition hover:-translate-y-0.5 hover:border-brand"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.provider} · {item.providerSkill}</p></div><span className="rounded-full bg-verified/10 px-2.5 py-1 text-xs font-bold text-verified">{score}% match</span></div><p className="mt-4 text-sm font-semibold text-brand">${item.price} · {item.turnaround}</p></button> : <button type="button" key={item.id} onClick={() => onHire(item)} className="rounded-2xl border border-border bg-card p-4 text-left transition hover:-translate-y-0.5 hover:border-brand"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><Avatar name={item.name} color={item.avatarColor} className="size-9 shrink-0 text-xs" /><div><p className="font-semibold">{item.name}</p><p className="text-sm text-muted-foreground">{item.primarySkill} · {item.major}</p></div></div><span className="rounded-full bg-verified/10 px-2.5 py-1 text-xs font-bold text-verified">{score}% match</span></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{item.tagline}</p></button>)}</div>{(isRecruiter ? rankedStudents : rankedGigs).length === 0 && <div className="mt-4 rounded-2xl border border-dashed border-border bg-card p-8 text-center text-sm text-muted-foreground">No direct matches yet. Try a broader description.</div>}</section> : <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-brand p-5 text-brand-foreground"><BriefcaseBusiness className="size-6" /><p className="mt-8 text-3xl font-bold">{isRecruiter ? '214' : '128'}</p><p className="mt-1 text-sm text-brand-foreground/80">active opportunities nearby</p></div><div className="rounded-2xl border border-border bg-card p-5"><CheckCircle2 className="size-6 text-verified" /><p className="mt-8 text-3xl font-bold">98%</p><p className="mt-1 text-sm text-muted-foreground">verified community members</p></div><div className="rounded-2xl border border-border bg-card p-5"><UserRound className="size-6 text-brand" /><p className="mt-8 text-3xl font-bold">4.9/5</p><p className="mt-1 text-sm text-muted-foreground">average completed-gig rating</p></div></section>}
      {query.trim() && rankedGigs.length === 0 && rankedStudents.length === 0 && <button type="button" className="mt-6 min-h-12 w-full rounded-xl border-2 border-dashed border-brand bg-accent px-4 text-sm font-bold text-brand transition hover:bg-brand hover:text-brand-foreground">No suitable match found — Post offer or availability</button>}
      <section className="mt-8 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-bold">25-trade marketplace seed</h2><p className="mt-1 text-sm text-muted-foreground">Every core service starts with active worker profiles and offers.</p></div><span className="rounded-full bg-verified/10 px-2.5 py-1 text-xs font-bold text-verified">Demo data</span></div><div className="mt-4 flex flex-wrap gap-2">{seededTradeCounts.map((trade) => <span key={trade.name} className="rounded-full border border-border bg-surface px-3 py-1.5 text-xs font-medium text-muted-foreground">{trade.name}</span>)}</div></section>
      <button type="button" onClick={onLogout} className="mt-10 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground transition hover:text-foreground"><ArrowLeft className="size-4" /> Sign out and return to login</button>
    </div>
  </main>
}
